package views;

public enum MenuCommand {	
	LOG_IN, SIGN_UP, NONE, EXIT, SHOW_ALL_USERS, SHOW_MY_COMMENTS, SHOW_MY_RECIPES,
	SHOW_ALL_CATEGORIES, SHOW_MY_CATEGORIES, ADD_CATEGORY, DELETE_CATEGORY,
	SHOW_RECIPES_BY_CATEGORY, ADD_RECIPE, DELETE_RECIPE, FIND_USERS_BY_ID,
	FIND_USERS_BY_USERNAME, DELETE_USER, MODIFY_USER, SHOW_FAVOURITE_COOKS,
	SHOW_FAVOURITE_RECIPES, UPDATE_USER, RETURN, SAVE, LOAD
}
